<a href="https://colab.research.google.com/github/sonhj110/Coding-Test/blob/main/topic_daily_news_volume.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/SK하이닉스/06. LDA 토픽모델링/sk_tokens_categorized.csv')
df.head

<bound method NDFrame.head of         Unnamed: 0        date  \
0                0  2018-10-02
1                1  2018-10-02
2                2  2018-10-02
3                3  2018-10-02
4                4  2018-10-02
...            ...         ...
133746      133746  2023-09-27
133747      133747  2023-09-27
133748      133748  2023-09-27
133749      133749  2023-09-27
133750      133750  2023-09-27

                                                 contents  \
0       - 22편. 게임엑스코인(GXC) <下> 김웅겸 대표 인터뷰- "블록체인 기술과 가...
1       SK텔레콤이 자회사 SK브로드밴드의 온라인 동영상 서비스(OTT) ‘옥수수’ 사업부...
2       【서울=뉴시스】  = 2일 오전 빅데이터로 분석한 주식시장 코스피 200종목의 시장...
3       삼성증권은 2일 SK하이닉스에 대해 예상치 못했던 현금흐름을 축적할 것으로 전망하며...
4       [한국경제TV ]10월 2일 SK하이닉스는 전일(73,100원) 대비 1,200원(...
...                                                   ...
133746  추경호 부총리 겸 기획재정부 장관(오른쪽 두 번째)이 27일 경기 이천에 있는 SK...
133747  9월 제조업 업황 BSI 1P 오른 68기계·장비·석유정제 업종이 견인전산업 업황 ...
133748  2022년 對中 반도체 장비 수출 통제상무부, 이르면 9월 내 통보 전망업체 사업 ...
133749  미, ‘장비 반입 규제’ 무기한 유예 가닥…내달 초 통보될 듯미국 정부가 삼성전자와...
133750  [앵커]미국 정부가 삼성전자와  SK하이닉스  중국 공장에  적용한 반도체 장비  ...

                                                   tokens  가장 비중이 높은 토픽
0       ['게임', '엑스', '코인', '김웅', '대표', '인터뷰', '블록체인', ...            28
1       ['텔레콤', '자회사', '브로드밴드', '온라인', '동영상', '서비스', '...            28
2       ['서울', '오전', '분석', '주식', '시장', '시장', '심리', '단계...            41
3       ['삼성증권', '하이닉스', '예상', '현금', '흐름', '축적', '전망',...            34
4       ['한국', '하이닉스', '대비', '시작', '한국', '한국', '거장', '...            28
...                                                   ...           ...
133746  ['추경호', '부총리', '기획', '재정부', '장관', '오른쪽', '경기',...            49
133747  ['제조업', '기계', '장비', '석유', '정제', '업종', '견인', '산...            49
133748  ['對中', '반도체', '장비', '수출', '통제', '상무부', '통보', '...            49
133749  ['장비', '반입', '규제', '무기', '유예', '가닥', '내달', '통보...            49
133750  ['미국', '정부', '삼성전자', '하이닉스', '중국', '공장', '적용',...            49

[133751 rows x 5 columns]>

In [ ]:
df['가장 비중이 높은 토픽'] = df['가장 비중이 높은 토픽'].astype(int)

In [ ]:
df['가장 비중이 높은 토픽'] = df['가장 비중이 높은 토픽'] + 1

In [ ]:
df.head

<bound method NDFrame.head of         Unnamed: 0        date  \
0                0  2018-10-02
1                1  2018-10-02
2                2  2018-10-02
3                3  2018-10-02
4                4  2018-10-02
...            ...         ...
133746      133746  2023-09-27
133747      133747  2023-09-27
133748      133748  2023-09-27
133749      133749  2023-09-27
133750      133750  2023-09-27

                                                 contents  \
0       - 22편. 게임엑스코인(GXC) <下> 김웅겸 대표 인터뷰- "블록체인 기술과 가...
1       SK텔레콤이 자회사 SK브로드밴드의 온라인 동영상 서비스(OTT) ‘옥수수’ 사업부...
2       【서울=뉴시스】  = 2일 오전 빅데이터로 분석한 주식시장 코스피 200종목의 시장...
3       삼성증권은 2일 SK하이닉스에 대해 예상치 못했던 현금흐름을 축적할 것으로 전망하며...
4       [한국경제TV ]10월 2일 SK하이닉스는 전일(73,100원) 대비 1,200원(...
...                                                   ...
133746  추경호 부총리 겸 기획재정부 장관(오른쪽 두 번째)이 27일 경기 이천에 있는 SK...
133747  9월 제조업 업황 BSI 1P 오른 68기계·장비·석유정제 업종이 견인전산업 업황 ...
133748  2022년 對中 반도체 장비 수출 통제상무부, 이르면 9월 내 통보 전망업체 사업 ...
133749  미, ‘장비 반입 규제’ 무기한 유예 가닥…내달 초 통보될 듯미국 정부가 삼성전자와...
133750  [앵커]미국 정부가 삼성전자와  SK하이닉스  중국 공장에  적용한 반도체 장비  ...

                                                   tokens  가장 비중이 높은 토픽
0       ['게임', '엑스', '코인', '김웅', '대표', '인터뷰', '블록체인', ...            29
1       ['텔레콤', '자회사', '브로드밴드', '온라인', '동영상', '서비스', '...            29
2       ['서울', '오전', '분석', '주식', '시장', '시장', '심리', '단계...            42
3       ['삼성증권', '하이닉스', '예상', '현금', '흐름', '축적', '전망',...            35
4       ['한국', '하이닉스', '대비', '시작', '한국', '한국', '거장', '...            29
...                                                   ...           ...
133746  ['추경호', '부총리', '기획', '재정부', '장관', '오른쪽', '경기',...            50
133747  ['제조업', '기계', '장비', '석유', '정제', '업종', '견인', '산...            50
133748  ['對中', '반도체', '장비', '수출', '통제', '상무부', '통보', '...            50
133749  ['장비', '반입', '규제', '무기', '유예', '가닥', '내달', '통보...            50
133750  ['미국', '정부', '삼성전자', '하이닉스', '중국', '공장', '적용',...            50

[133751 rows x 5 columns]>

In [ ]:
pivot = df.groupby(['가장 비중이 높은 토픽', 'date']).size().unstack(fill_value=0)

In [ ]:
pivot

date,2018-10-02,2018-10-04,2018-10-05,2018-10-08,2018-10-10,2018-10-11,2018-10-12,2018-10-15,2018-10-16,2018-10-17,...,2023-09-14,2023-09-15,2023-09-18,2023-09-19,2023-09-20,2023-09-21,2023-09-22,2023-09-25,2023-09-26,2023-09-27
가장 비중이 높은 토픽,,,,,,,,,,,,,,,,,,,,,
1,7,17,10,8,14,34,16,13,3,10,...,11,7,6,9,6,25,13,12,13,21
2,12,17,15,24,20,18,18,17,19,12,...,11,10,9,7,6,3,8,5,7,6
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,2,1,0,1,3,4,0,0,0,2,...,0,1,3,0,0,0,0,1,0,1
7,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,0,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,1,0,0,0,0,0
11,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,1,61,1,1,0,0,1,1,0,0,...,1,4,0,2,0,0,13,1,1,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,9,0,0,0,0,0,...,0,0,22,1,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,1,3,2,2,4,7,3,0,4,1,...,1,4,8,3,5,2,2,2,3,4
20,10,6,5,12,3,26,17,6,4,11,...,8,6,18,18,11,2,15,3,7,6
21,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,46,6,1,16,6,5,29,0,23,...,4,1,14,7,2,14,15,13,14,2
29,5,4,6,11,5,5,8,4,4,7,...,6,2,9,6,1,1,2,3,4,6
30,0,1,0,0,4,0,0,1,2,0,...,1,0,1,15,1,2,0,2,0,1
32,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,5,9,5,6,11,12,8,8,7,5,...,4,3,6,2,5,3,4,2,4,4
34,0,0,0,4,0,0,0,1,0,5,...,0,0,0,0,27,2,0,0,0,0
35,1,2,14,3,10,20,0,8,2,3,...,10,7,14,11,3,6,2,3,3,9
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,2,4,0,3,1,3,1,4,1,21,...,3,2,3,3,6,1,2,2,1,1
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,0,75,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
42,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
44,2,23,4,2,2,0,1,1,7,9,...,24,1,24,7,3,5,3,2,8,5
45,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,0,13,0,2,2,5,1,2,1,1,...,1,18,0,0,2,3,0,1,9,2
49,0,0,0,0,6,0,0,0,11,8,...,0,0,4,0,0,0,0,0,0,1
50,5,224,33,2,45,10,5,5,6,8,...,19,53,19,27,21,18,45,63,13,135

In [ ]:
pivot.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40 entries, 0 to 49
Columns: 1234 entries, 2018-10-02 to 2023-09-27
dtypes: int64(1234)
memory usage: 385.9 KB

In [ ]:
count = (pivot >= 1).sum(axis=1)

가장 비중이 높은 토픽
1     1224
2     1232
3       77
4       23
6      439
7       49
9      137
10      33
11      73
12       1
14     720
15      28
16      62
17       2
19    1097
20    1228
21      83
22       2
23       2
25       2
26       2
28    1132
29    1208
30     713
32      79
33    1201
34     233
35    1128
36       2
37       1
38       2
39     962
40       1
41      84
42     901
44    1061
45       5
47     872
49     159
50    1234
dtype: int64

In [ ]:
topic_list = [1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,18,19,20,21,28,31,33,35,39,44,46,47,48,49]

In [ ]:
mask = df['가장 비중이 높은 토픽'].isin(topic_list)
filtered_df = df[mask]
print(filtered_df)

        Unnamed: 0        date  \
3                3  2018-10-02
5                5  2018-10-02
6                6  2018-10-02
7                7  2018-10-02
8                8  2018-10-02
...            ...         ...
133721      133721  2023-09-27
133728      133728  2023-09-27
133735      133735  2023-09-27
133737      133737  2023-09-27
133741      133741  2023-09-27

                                                 contents  \
3       삼성증권은 2일 SK하이닉스에 대해 예상치 못했던 현금흐름을 축적할 것으로 전망하며...
5       [한국경제TV ][코스피 개장 시황]10월 2일 코스피는 전일 대비 6.57p(0....
6       = 코스피가 2일 하락 출발한 뒤 보합권에서 혼조 흐름을 보이고 있다.     코스...
7       [머니투데이 ] 코스피는 외국인과 기관 매도에 약보합세를 나타내고 있다. 3분기 실...
8       외국인·기관 `팔자`…금융업 등 대다수 하락시총상위株 약세…SK하이닉스 ·삼성바이오...
...                                                   ...
133721  ⓒ News1 윤주희 디자이너(서울=뉴스1)  = 국내 증시가 27일 최근 하락세를...
133728  연휴 앞두고 코스피지수 0.09% 오른 2465.07 마감외국인 순매도는 8거래일 ...
133735  [내일의 전략]    (서울=뉴스1)  = 27일 오후 서울 중구 하나은행 명동점 ...
133737  추경호 부총리 겸 기획재정부 장관이 27일 오전 경기도 이천시 SK하이닉스에서 열린...
133741  4분기부터 메모리 반도체 가격 상승세 전환 전망삼성·SK, HBM 등 고성능 칩 '...

                                                   tokens  가장 비중이 높은 토픽
3       ['삼성증권', '하이닉스', '예상', '현금', '흐름', '축적', '전망',...            35
5       ['한국', '개장', '시황', '대비', '시작', '현재', '시각', '전체...             2
6       ['출발', '보합', '혼조', '흐름', '제작', '최자윤', '일러스트', ...            20
7       ['머니', '매도', '약보합세', '실적', '시즌', '개막', '실적', '...             2
8       ['팔자', '금융업', '약세', '하이닉스', '삼성', '바이오', '로직스'...            33
...                                                   ...           ...
133721  ['윤주희', '디자이너', '서울', '뉴스', '국내', '증시', '최근', ...             1
133728  ['연휴', '연속', '장기', '우려', '장중', '돌파', '고유', '실적...            35
133735  ['내일', '전략', '서울', '뉴스', '오후', '서울', '은행', '딜링...             2
133737  ['추경호', '부총리', '기획', '재정부', '장관', '오전', '이천시',...             1
133741  ['메모리', '반도체', '상승세', '전환', '전망', '삼성', '성능', ...            19

[89776 rows x 5 columns]

In [ ]:
# filtered_df.drop('Unnamed: 0', axis=1, inplace=True)
# filtered_df.info
filtered_df.to_csv('/content/drive/MyDrive/SK하이닉스/07. LASSO 회귀/filtered_sk_data.csv')